namespace ServiceDesk.Core.Models;

/// <summary>
/// One row per inbound Gmail message the poller saw — whether it created a
/// ticket, threaded into an existing one, or got skipped (and why). This is
/// the diagnostic counterpart to <see cref="NotificationLog"/> (which only
/// records outbound sends). Without this it took a week to notice that the
/// May 6 outage had silently dropped every incoming email.
/// </summary>
public class InboundEmailLog
{
    public int Id { get; set; }

    /// <summary>FK to the EmailConfiguration whose poll cycle saw this message.</summary>
    public int? EmailConfigurationId { get; set; }

    /// <summary>Gmail's per-message id (not the RFC 2822 Message-Id).</summary>
    public string GmailMessageId { get; set; } = string.Empty;

    /// <summary>RFC 2822 Message-Id (for threading lookups).</summary>
    public string? MessageId { get; set; }

    public string? Subject     { get; set; }
    public string? FromAddress { get; set; }

    /// <summary>Gmail internalDate parsed from the message envelope.</summary>
    public DateTime? ReceivedDate { get; set; }

    public DateTime ProcessedDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// What the poller did with this message. Stored as the enum name string
    /// so a new outcome doesn't need a migration. Matches <see cref="InboundAction"/>.
    /// </summary>
    public string Action { get; set; } = "Unknown";

    /// <summary>
    /// Human-readable context for the action — e.g. "Ticket #1234" for
    /// TicketCreated, "Threaded to #5678 (subject fallback)" for NoteAppended,
    /// or "Older than 72h cutoff" for SkippedStale.
    /// </summary>
    public string? ActionDetail { get; set; }

    /// <summary>Exception message when Action == "Failed".</summary>
    public string? ErrorMessage { get; set; }

    public EmailConfiguration? EmailConfiguration { get; set; }
}

/// <summary>
/// Outcome categories for an inbound message — kept as a separate type so the
/// view layer can group and filter without parsing strings.
/// </summary>
public enum InboundAction
{
    Unknown            = 0,
    TicketCreated      = 1,
    NoteAppended       = 2,
    SkippedDuplicate   = 3,
    SkippedSelf        = 4,
    SkippedAutoGenerated = 5,
    SkippedAutoReply   = 6,
    SkippedStale       = 7,
    SkippedNoCreate    = 8, // CreateTicketsFromEmails was false and no thread matched
    Failed             = 9
}
