using Ganss.Xss;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ServiceDesk.Core.Enums;
using ServiceDesk.Core.Models;
using ServiceDesk.Infrastructure.Data;

namespace ServiceDesk.Web.Services;

public class GmailApiService : BackgroundService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<GmailApiService> _logger;
    private readonly IHttpClientFactory _httpClientFactory;

    // Regex to match ticket reference [#SS-12345] in subject
    private static readonly Regex TicketRefRegex = new(@"\[#SS-(\d+)\]", RegexOptions.Compiled);

    // Header to identify our own outgoing emails (anti-loop)
    private const string AutoGeneratedHeader = "X-ServiceSphere-AutoGenerated";

    public GmailApiService(IServiceProvider serviceProvider, ILogger<GmailApiService> logger, IHttpClientFactory httpClientFactory)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
        _httpClientFactory = httpClientFactory;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Gmail API Polling Service started.");

        // Wait a bit on startup to let the app initialize
        await Task.Delay(TimeSpan.FromSeconds(10), stoppingToken);

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await PollAllMailboxes(stoppingToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in Gmail polling loop.");
            }

            await Task.Delay(TimeSpan.FromMinutes(1), stoppingToken);
        }
    }

    private async Task PollAllMailboxes(CancellationToken stoppingToken)
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<ServiceDeskDbContext>();

        // Don't gate on IsAuthorized here — the field gets auto-flipped to false
        // whenever a token refresh fails for ANY reason (network blip, 5xx,
        // rate limit), which used to permanently freeze polling until an admin
        // manually re-authorised. We keep polling so long as we still hold a
        // refresh token (admin "Revoke" wipes the token, so that path is
        // honoured). Genuine token revocation by Google is detected by the
        // invalid_grant response inside EnsureValidAccessToken below.
        var configs = await context.EmailConfigurations
            .Where(c => c.IsActive && c.GmailRefreshToken != null)
            .ToListAsync(stoppingToken);

        foreach (var config in configs)
        {
            if (config.LastPolledDate.HasValue &&
                DateTime.UtcNow - config.LastPolledDate.Value < TimeSpan.FromMinutes(config.PollIntervalMinutes))
            {
                continue;
            }

            try
            {
                await PollGmailInbox(context, config, stoppingToken);
                config.LastPolledDate          = DateTime.UtcNow;
                config.LastSuccessfulPollDate  = DateTime.UtcNow;
                config.LastError               = null;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error polling Gmail inbox {Email}", config.EmailAddress);
                config.LastError      = $"{DateTime.UtcNow:g}: {ex.Message}";
                config.LastPolledDate = DateTime.UtcNow;
                // Deliberately NOT updating LastSuccessfulPollDate here — that's
                // the whole point of the new column.
            }

            await context.SaveChangesAsync(stoppingToken);
        }
    }

    private async Task PollGmailInbox(ServiceDeskDbContext context, EmailConfiguration config, CancellationToken stoppingToken)
    {
        var accessToken = await EnsureValidAccessToken(context, config, stoppingToken);
        if (string.IsNullOrEmpty(accessToken))
        {
            _logger.LogWarning("Could not obtain valid access token for {Email}", config.EmailAddress);
            return;
        }

        using var httpClient = _httpClientFactory.CreateClient();
        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

        // If we have a historyId, use history-based incremental sync
        // Otherwise, fetch recent unread messages
        List<GmailMessage> messages;
        if (!string.IsNullOrEmpty(config.GmailHistoryId))
        {
            messages = await GetMessagesSinceHistory(httpClient, config, stoppingToken);
        }
        else
        {
            messages = await GetUnreadMessages(httpClient, config, stoppingToken);
        }

        _logger.LogInformation("Found {Count} messages to process for {Email}", messages.Count, config.EmailAddress);

        foreach (var gmailMsg in messages)
        {
            if (stoppingToken.IsCancellationRequested) break;

            try
            {
                await ProcessMessage(context, config, httpClient, gmailMsg, stoppingToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing Gmail message {MessageId}", gmailMsg.Id);
                // Surface processing failures in the inbound log too — the
                // outer catch was the only thing logging this class of error
                // before, which is why the May 6 outage went unnoticed.
                WriteInboundLog(context, config, gmailMsg, null, null, null, null,
                    InboundAction.Failed,
                    detail: "Exception during ProcessMessage.",
                    error: ex.Message);
            }
        }

        await context.SaveChangesAsync(stoppingToken);
    }

    private async Task ProcessMessage(ServiceDeskDbContext context, EmailConfiguration config,
        HttpClient httpClient, GmailMessage gmailMsg, CancellationToken stoppingToken)
    {
        // Get full message details
        var fullMessage = await GetMessageDetails(httpClient, gmailMsg.Id, stoppingToken);
        if (fullMessage == null)
        {
            WriteInboundLog(context, config, gmailMsg, null, null, null, null,
                InboundAction.Failed,
                detail: "GetMessageDetails returned null — see prior log entries for the cause.");
            return;
        }

        var headers = fullMessage.Payload?.Headers ?? new List<GmailHeader>();
        var messageId = GetHeader(headers, "Message-ID") ?? GetHeader(headers, "Message-Id");
        var subject = GetHeader(headers, "Subject") ?? "(No Subject)";
        var from = GetHeader(headers, "From") ?? "";
        var inReplyTo = GetHeader(headers, "In-Reply-To");
        var references = GetHeader(headers, "References");

        // ---- GUARDRAIL 0: Age gate — skip emails older than 72 hours ----
        // Prevents a reset historyId or a flooded inbox from creating tickets from
        // weeks-old messages. internalDate is ms since Unix epoch; 0 means unknown.
        if (fullMessage.InternalDate > 0)
        {
            var emailAge = DateTimeOffset.UtcNow - DateTimeOffset.FromUnixTimeMilliseconds(fullMessage.InternalDate);
            if (emailAge.TotalHours > 72)
            {
                _logger.LogInformation("Skipping old email ({Age:0}h): {Subject}", emailAge.TotalHours, subject);
                WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, from,
                    InboundAction.SkippedStale,
                    detail: $"Email is {emailAge.TotalHours:0}h old; cutoff is 72h.");
                UpdateHistoryId(config, fullMessage.HistoryId);
                return;
            }
        }

        // Parse sender email and name
        var (fromEmail, fromName) = ParseEmailAddress(from);

        // ---- GUARDRAIL 1: Anti-loop - ignore our own outgoing emails ----
        if (fromEmail.Equals(config.EmailAddress, StringComparison.OrdinalIgnoreCase))
        {
            _logger.LogDebug("Skipping self-sent email: {Subject}", subject);
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.SkippedSelf,
                detail: $"Sender matches mailbox address ({config.EmailAddress}).");
            UpdateHistoryId(config, fullMessage.HistoryId);
            return;
        }

        // ---- GUARDRAIL 2: Check for our auto-generated header ----
        var autoGenHeader = GetHeader(headers, AutoGeneratedHeader);
        if (!string.IsNullOrEmpty(autoGenHeader))
        {
            _logger.LogDebug("Skipping ServiceSphere-generated email: {Subject}", subject);
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.SkippedAutoGenerated,
                detail: $"{AutoGeneratedHeader} header present.");
            UpdateHistoryId(config, fullMessage.HistoryId);
            return;
        }

        // ---- GUARDRAIL 3: Anti-duplicate - check if Message-ID already processed ----
        if (!string.IsNullOrEmpty(messageId))
        {
            var alreadyProcessed = await context.TicketEmails
                .AnyAsync(te => te.MessageId == messageId, stoppingToken);
            if (alreadyProcessed)
            {
                _logger.LogDebug("Skipping already-processed email: {MessageId}", messageId);
                WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                    InboundAction.SkippedDuplicate,
                    detail: $"Message-Id {messageId} already in TicketEmails.");
                UpdateHistoryId(config, fullMessage.HistoryId);
                return;
            }
        }

        // Also check by GmailMessageId
        var gmailIdProcessed = await context.TicketEmails
            .AnyAsync(te => te.GmailMessageId == gmailMsg.Id, stoppingToken);
        if (gmailIdProcessed)
        {
            _logger.LogDebug("Skipping already-processed Gmail message: {GmailId}", gmailMsg.Id);
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.SkippedDuplicate,
                detail: $"Gmail message id {gmailMsg.Id} already in TicketEmails.");
            UpdateHistoryId(config, fullMessage.HistoryId);
            return;
        }

        // ---- GUARDRAIL 4: Ignore common auto-replies and mailer-daemons ----
        if (IsAutoReply(headers, fromEmail))
        {
            _logger.LogDebug("Skipping auto-reply/bounce email from: {From}", fromEmail);
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.SkippedAutoReply,
                detail: $"Auto-reply indicators present (Auto-Submitted / Precedence / noreply-style sender).");
            UpdateHistoryId(config, fullMessage.HistoryId);
            return;
        }

        // Extract body content — plain text for storage/searching, HTML for display
        var body     = ExtractPlainBody(fullMessage);
        var bodyHtml = ExtractHtmlBody(fullMessage);

        // ---- THREADING: Check subject for [#SS-XXXXX] ----
        var ticketMatch = TicketRefRegex.Match(subject);
        int? existingTicketId = null;

        if (ticketMatch.Success && int.TryParse(ticketMatch.Groups[1].Value, out var parsedId))
        {
            // Verify ticket actually exists
            var ticketExists = await context.Tickets.AnyAsync(t => t.Id == parsedId, stoppingToken);
            if (ticketExists)
            {
                existingTicketId = parsedId;
            }
        }

        // If no subject match, try In-Reply-To / References header threading
        if (!existingTicketId.HasValue && !string.IsNullOrEmpty(inReplyTo))
        {
            var relatedEmail = await context.TicketEmails
                .FirstOrDefaultAsync(te => te.MessageId == inReplyTo, stoppingToken);
            if (relatedEmail != null)
            {
                existingTicketId = relatedEmail.TicketId;
            }
        }

        if (!existingTicketId.HasValue && !string.IsNullOrEmpty(references))
        {
            // Check all referenced message IDs
            var refIds = references.Split(new[] { ' ', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var refId in refIds)
            {
                var relatedEmail = await context.TicketEmails
                    .FirstOrDefaultAsync(te => te.MessageId == refId.Trim(), stoppingToken);
                if (relatedEmail != null)
                {
                    existingTicketId = relatedEmail.TicketId;
                    break;
                }
            }
        }

        // ---- THREADING FALLBACK: match clean subject against recent open tickets ----
        // Catches forwarded emails and replies that bypass the three header-based checks above.
        if (!existingTicketId.HasValue)
        {
            var cleanedSubject = CleanSubject(subject);
            if (!string.IsNullOrWhiteSpace(cleanedSubject))
            {
                var cutoff = DateTime.UtcNow.AddDays(-14);
                var subjectMatch = await context.Tickets
                    .Where(t => t.Title == cleanedSubject
                             && t.CreatedDate >= cutoff
                             && t.Status != TicketStatus.Closed
                             && t.Status != TicketStatus.Cancelled)
                    .OrderByDescending(t => t.CreatedDate)
                    .Select(t => (int?)t.Id)
                    .FirstOrDefaultAsync(stoppingToken);
                if (subjectMatch.HasValue)
                {
                    existingTicketId = subjectMatch.Value;
                    _logger.LogInformation(
                        "Threaded email to Ticket #{TicketId} via subject fallback: {Subject}",
                        existingTicketId.Value, cleanedSubject);
                }
            }
        }

        if (existingTicketId.HasValue)
        {
            // ---- APPEND NOTE TO EXISTING TICKET ----
            var note = new TicketNote
            {
                TicketId = existingTicketId.Value,
                AuthorName = fromName ?? fromEmail,
                AuthorEmail = fromEmail,
                Content = body,
                ContentHtml = bodyHtml,
                Source = "Email",
                IsInternal = false,
                CreatedDate = DateTime.UtcNow
            };
            context.TicketNotes.Add(note);

            // Update ticket's UpdatedDate
            var ticket = await context.Tickets.FindAsync(new object[] { existingTicketId.Value }, stoppingToken);
            if (ticket != null)
            {
                ticket.UpdatedDate = DateTime.UtcNow;
            }

            _logger.LogInformation("Added email reply as note to Ticket #{TicketId}: {Subject}",
                existingTicketId.Value, subject);
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.NoteAppended,
                detail: $"Threaded into Ticket #{existingTicketId.Value}.");
        }
        else if (config.CreateTicketsFromEmails)
        {
            // ---- CREATE NEW TICKET ----
            var submitter = await context.Employees
                .Include(e => e.Branch)
                .FirstOrDefaultAsync(e => e.Email == fromEmail, stoppingToken);

            // Clean subject (remove Re:, Fwd:, etc.)
            var cleanSubject = CleanSubject(subject);
            if (cleanSubject.Length > 200)
                cleanSubject = cleanSubject[..200];

            // Resolve assignee via rules (category + submitter branch), fallback to config default
            int? submitterBranchId = submitter?.BranchId;
            var resolver = _serviceProvider.CreateScope().ServiceProvider
                .GetRequiredService<AssignmentResolverService>();

            // Detect category from email content (DB-backed keywords, hardcoded fallback)
            var detectedCategory = await resolver.DetectCategoryAsync(cleanSubject, body);

            var resolvedAssigneeId = await resolver.ResolveAsync(
                detectedCategory, submitterBranchId, config.DefaultAssigneeId);

            _logger.LogInformation(
                "Inbound email: category detected={Category}, branch={BranchId}, resolved assignee={AssigneeId}",
                detectedCategory, submitterBranchId, resolvedAssigneeId);

            var ticket = new Ticket
            {
                Title = string.IsNullOrWhiteSpace(cleanSubject) ? "Email Ticket (No Subject)" : cleanSubject,
                Description    = body.Length > 2000 ? body[..2000] : body,
                DescriptionHtml = bodyHtml,
                Category = detectedCategory,
                Status = TicketStatus.Open,
                Priority = TicketPriority.Medium,
                CreatedDate = DateTime.UtcNow,
                SubmittedById = submitter?.Id ?? config.DefaultAssigneeId ?? 1,
                BranchId = submitterBranchId,
                AssignedToId = resolvedAssigneeId,
            };

            context.Tickets.Add(ticket);
            await context.SaveChangesAsync(stoppingToken); // Save to get ticket.Id

            // Add the initial note
            var note = new TicketNote
            {
                TicketId = ticket.Id,
                AuthorName = fromName ?? fromEmail,
                AuthorEmail = fromEmail,
                Content = body,
                ContentHtml = bodyHtml,
                Source = "Email",
                IsInternal = false,
                CreatedDate = DateTime.UtcNow
            };
            context.TicketNotes.Add(note);

            _logger.LogInformation("Created new Ticket #{TicketId} from email: {Subject}", ticket.Id, ticket.Title);
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.TicketCreated,
                detail: $"Created Ticket #{ticket.Id} (category {detectedCategory}, assignee {resolvedAssigneeId?.ToString() ?? "(unassigned)"}).");

            // Run ML.NET triage (category + priority prediction) in background — same as manual create
            _ = Task.Run(async () =>
            {
                try
                {
                    using var triageScope = _serviceProvider.CreateScope();
                    var triage = triageScope.ServiceProvider.GetRequiredService<AiTriageService>();
                    await triage.TriageAndSaveAsync(ticket.Id, ticket.Title, ticket.Description ?? "", ticket.BranchId);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "[EmailTriage] Background triage failed for Ticket #{Id}", ticket.Id);
                }
            });

            // Check for possible duplicate tickets (>80% TF-IDF similarity) — post an internal note
            _ = Task.Run(async () =>
            {
                try
                {
                    using var dupScope = _serviceProvider.CreateScope();
                    var similarity = dupScope.ServiceProvider.GetRequiredService<TicketSimilarityService>();
                    var db         = dupScope.ServiceProvider.GetRequiredService<ServiceDeskDbContext>();
                    var similar    = await similarity.FindSimilarAsync(
                        ticket.Title, ticket.Description, excludeTicketId: ticket.Id, topN: 3);
                    var dupes = similar.Where(s => s.ScorePct >= 80).ToList();
                    if (dupes.Count == 0) return;

                    var links = string.Join(", ", dupes.Select(d => $"#{d.TicketId} ({d.ScorePct:F0}% match)"));
                    db.TicketNotes.Add(new TicketNote
                    {
                        TicketId    = ticket.Id,
                        AuthorName  = "AI Duplicate Detector",
                        Content     = $"🔁 Possible duplicate detected. Similar open tickets: {links}. "
                                    + "Consider merging or linking before working this ticket.",
                        Source      = "AI",
                        IsInternal  = true,
                        CreatedDate = DateTime.UtcNow,
                    });
                    await db.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "[DuplicateCheck] Failed for Ticket #{Id}", ticket.Id);
                }
            });

            // Send auto-reply confirmation with ticket reference
            if (config.AutoReplyOnNewTicket)
            {
                try
                {
                    var notificationService = _serviceProvider.CreateScope().ServiceProvider
                        .GetRequiredService<EmailNotificationService>();
                    await notificationService.SendTicketCreatedConfirmation(ticket, fromEmail, fromName ?? fromEmail);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Failed to send auto-reply for Ticket #{TicketId}", ticket.Id);
                }
            }

            // Notify assigned agent about the new ticket
            if (resolvedAssigneeId.HasValue)
            {
                try
                {
                    var ticketWithAssignee = await context.Tickets
                        .Include(t => t.AssignedTo)
                        .AsNoTracking()
                        .FirstOrDefaultAsync(t => t.Id == ticket.Id, stoppingToken);
                    if (ticketWithAssignee?.AssignedTo != null)
                    {
                        var notifySvc = _serviceProvider.CreateScope().ServiceProvider
                            .GetRequiredService<EmailNotificationService>();
                        await notifySvc.NotifyTicketAssigned(ticketWithAssignee);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Failed to send assignment notification for Ticket #{TicketId}", ticket.Id);
                }
            }

            existingTicketId = ticket.Id;
        }
        else
        {
            // No thread match AND CreateTicketsFromEmails is disabled — note
            // the inbound for the audit log so admins can see why nothing
            // happened. We still mark-as-read and advance historyId so the
            // same message doesn't keep getting reconsidered.
            WriteInboundLog(context, config, gmailMsg, fullMessage, messageId, subject, fromEmail,
                InboundAction.SkippedNoCreate,
                detail: "No matching thread and CreateTicketsFromEmails is disabled.");
        }

        // Record the email for threading
        if (existingTicketId.HasValue)
        {
            var ticketEmail = new TicketEmail
            {
                TicketId = existingTicketId.Value,
                GmailMessageId = gmailMsg.Id,
                MessageId = messageId,
                InReplyTo = inReplyTo,
                References = references,
                FromAddress = fromEmail,
                FromName = fromName,
                Subject = subject.Length > 500 ? subject[..500] : subject,
                Direction = "Inbound",
                ProcessedDate = DateTime.UtcNow
            };
            context.TicketEmails.Add(ticketEmail);
        }

        // Mark message as read in Gmail
        await MarkAsRead(httpClient, gmailMsg.Id, stoppingToken);

        // Update historyId
        UpdateHistoryId(config, fullMessage.HistoryId);
    }

    #region Gmail API Helpers

    /// <summary>
    /// Ensures we have a valid (non-expired) access token, refreshing if needed.
    /// </summary>
    public async Task<string?> EnsureValidAccessToken(ServiceDeskDbContext context, EmailConfiguration config, CancellationToken ct)
    {
        if (string.IsNullOrEmpty(config.GmailRefreshToken) ||
            string.IsNullOrEmpty(config.GmailClientId) ||
            string.IsNullOrEmpty(config.GmailClientSecret))
        {
            return null;
        }

        // If access token is still valid, use it
        if (!string.IsNullOrEmpty(config.GmailAccessToken) &&
            config.GmailTokenExpiry.HasValue &&
            config.GmailTokenExpiry.Value > DateTime.UtcNow.AddMinutes(2))
        {
            return config.GmailAccessToken;
        }

        // Refresh the token
        using var httpClient = _httpClientFactory.CreateClient();
        var tokenRequest = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            ["client_id"] = config.GmailClientId,
            ["client_secret"] = config.GmailClientSecret,
            ["refresh_token"] = config.GmailRefreshToken,
            ["grant_type"] = "refresh_token"
        });

        var response = await httpClient.PostAsync("https://oauth2.googleapis.com/token", tokenRequest, ct);
        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync(ct);
            _logger.LogError("Failed to refresh Gmail token for {Email}: {Error}",
                config.EmailAddress, errorBody);
            config.LastError = $"{DateTime.UtcNow:g}: OAuth token refresh failed ({(int)response.StatusCode}): {errorBody}";

            // Only auto-disable the integration when Google explicitly tells us
            // the refresh token itself is no longer usable (invalid_grant). For
            // every other failure — transient 5xx, rate limiting, network
            // hiccup — leave IsAuthorized alone so the next poll cycle retries
            // automatically. The previous behaviour froze the integration on
            // any failure and required a manual re-auth, which is what caused
            // the May 6 "no new tickets" outage.
            if (IsInvalidGrantResponse(errorBody))
            {
                config.IsAuthorized = false;
                _logger.LogError(
                    "Gmail refresh token for {Email} is invalid (invalid_grant). " +
                    "Admin must re-authorize the integration.", config.EmailAddress);
            }

            await context.SaveChangesAsync(ct);
            return null;
        }

        var tokenJson = await response.Content.ReadAsStringAsync(ct);
        var tokenData = JsonSerializer.Deserialize<JsonElement>(tokenJson);

        config.GmailAccessToken = tokenData.GetProperty("access_token").GetString();
        var expiresIn = tokenData.GetProperty("expires_in").GetInt32();
        config.GmailTokenExpiry = DateTime.UtcNow.AddSeconds(expiresIn);

        // If a new refresh token is provided, update it
        if (tokenData.TryGetProperty("refresh_token", out var newRefresh))
        {
            config.GmailRefreshToken = newRefresh.GetString();
        }

        // Refresh succeeded — clear any stale auth flag from a prior transient
        // failure so the admin UI reflects the current healthy state.
        config.IsAuthorized = true;
        config.LastError    = null;

        await context.SaveChangesAsync(ct);
        return config.GmailAccessToken;
    }

    /// <summary>
    /// Recognises Google's "this refresh token is permanently dead" error from
    /// the OAuth response body. Used so we only auto-disable the integration
    /// for genuine revocation, not transient errors.
    /// </summary>
    private static bool IsInvalidGrantResponse(string responseBody)
    {
        if (string.IsNullOrEmpty(responseBody)) return false;
        try
        {
            var doc = JsonSerializer.Deserialize<JsonElement>(responseBody);
            if (doc.ValueKind == JsonValueKind.Object &&
                doc.TryGetProperty("error", out var errEl) &&
                errEl.ValueKind == JsonValueKind.String)
            {
                return string.Equals(errEl.GetString(), "invalid_grant", StringComparison.OrdinalIgnoreCase);
            }
        }
        catch
        {
            // Fall through to the substring check below.
        }
        return responseBody.IndexOf("invalid_grant", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>
    /// Fetches messages that arrived since the stored historyId (incremental sync).
    /// </summary>
    private async Task<List<GmailMessage>> GetMessagesSinceHistory(HttpClient httpClient, EmailConfiguration config, CancellationToken ct)
    {
        var messages = new List<GmailMessage>();
        try
        {
            var url = $"https://gmail.googleapis.com/gmail/v1/users/me/history?startHistoryId={config.GmailHistoryId}&historyTypes=messageAdded&labelIds=INBOX";
            var response = await httpClient.GetAsync(url, ct);

            if (!response.IsSuccessStatusCode)
            {
                // If historyId is invalid (too old), fall back to unread messages
                _logger.LogWarning("History sync failed, falling back to unread messages.");
                config.GmailHistoryId = null;
                return await GetUnreadMessages(httpClient, config, ct);
            }

            var json = await response.Content.ReadAsStringAsync(ct);
            var data = JsonSerializer.Deserialize<JsonElement>(json);

            if (data.TryGetProperty("history", out var historyArr))
            {
                foreach (var history in historyArr.EnumerateArray())
                {
                    if (history.TryGetProperty("messagesAdded", out var added))
                    {
                        foreach (var msg in added.EnumerateArray())
                        {
                            if (msg.TryGetProperty("message", out var msgObj))
                            {
                                var id = msgObj.GetProperty("id").GetString();
                                if (id != null)
                                    messages.Add(new GmailMessage { Id = id });
                            }
                        }
                    }
                }
            }

            // Update historyId
            if (data.TryGetProperty("historyId", out var newHistoryId))
            {
                config.GmailHistoryId = newHistoryId.GetString();
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching Gmail history.");
            config.GmailHistoryId = null;
            return await GetUnreadMessages(httpClient, config, ct);
        }

        return messages;
    }

    /// <summary>
    /// Fetches unread messages from the inbox (initial sync or fallback).
    /// Scoped to the last 48 hours so a stale historyId never causes a flood of old messages.
    /// </summary>
    private async Task<List<GmailMessage>> GetUnreadMessages(HttpClient httpClient, EmailConfiguration config, CancellationToken ct)
    {
        var messages = new List<GmailMessage>();

        // Dynamic lookback window:
        //   - Anchor to the last *successful* poll minus 1 h (safety overlap).
        //   - Floor at "now - 14 days" so we never re-process months of mail
        //     if LastSuccessfulPollDate is null or absurdly old (e.g. DB
        //     restored from a backup).
        //   - The 14-day cap matches the fallback used when no watermark
        //     exists at all (fresh install).
        var hardFloor   = DateTime.UtcNow.AddDays(-14);
        var watermark   = config.LastSuccessfulPollDate?.AddHours(-1) ?? hardFloor;
        var lookbackUtc = watermark < hardFloor ? hardFloor : watermark;
        var after       = new DateTimeOffset(DateTime.SpecifyKind(lookbackUtc, DateTimeKind.Utc)).ToUnixTimeSeconds();

        var url = $"https://gmail.googleapis.com/gmail/v1/users/me/messages?q=is:unread+in:inbox+after:{after}&maxResults=100";
        var response = await httpClient.GetAsync(url, ct);

        if (!response.IsSuccessStatusCode) return messages;

        var json = await response.Content.ReadAsStringAsync(ct);
        var data = JsonSerializer.Deserialize<JsonElement>(json);

        if (data.TryGetProperty("messages", out var msgArr))
        {
            foreach (var msg in msgArr.EnumerateArray())
            {
                var id = msg.GetProperty("id").GetString();
                if (id != null)
                    messages.Add(new GmailMessage { Id = id });
            }
        }

        return messages;
    }

    /// <summary>
    /// Gets full message details including headers and body.
    /// </summary>
    private async Task<GmailFullMessage?> GetMessageDetails(HttpClient httpClient, string messageId, CancellationToken ct)
    {
        var url = $"https://gmail.googleapis.com/gmail/v1/users/me/messages/{messageId}?format=full";
        var response = await httpClient.GetAsync(url, ct);

        if (!response.IsSuccessStatusCode)
        {
            _logger.LogWarning("Gmail message fetch failed: {MessageId} returned {Status}",
                messageId, (int)response.StatusCode);
            return null;
        }

        var json = await response.Content.ReadAsStringAsync(ct);
        try
        {
            return JsonSerializer.Deserialize<GmailFullMessage>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                // Gmail returns internalDate / sizeEstimate / historyId etc. as
                // *string-encoded* numbers (e.g. "1746556800000"). Without this
                // option the deserializer throws a JsonException for those fields,
                // which silently skipped every inbound message — the real cause
                // of the "no new tickets since May 6" outage.
                NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString
            });
        }
        catch (JsonException ex)
        {
            // Surface deserialization failures loudly. Returning null silently
            // (the previous behaviour) is how the May 6 outage went undetected
            // for over a week.
            _logger.LogError(ex,
                "Failed to deserialize Gmail message {MessageId}. Body preview: {Preview}",
                messageId,
                json.Length > 500 ? json[..500] : json);
            return null;
        }
    }

    /// <summary>
    /// Marks a Gmail message as read by removing the UNREAD label.
    /// </summary>
    private async Task MarkAsRead(HttpClient httpClient, string messageId, CancellationToken ct)
    {
        var url = $"https://gmail.googleapis.com/gmail/v1/users/me/messages/{messageId}/modify";
        var body = JsonSerializer.Serialize(new { removeLabelIds = new[] { "UNREAD" } });
        var content = new StringContent(body, Encoding.UTF8, "application/json");
        await httpClient.PostAsync(url, content, ct);
    }

    /// <summary>
    /// Sends an email via Gmail API with proper threading headers.
    /// </summary>
    public async Task<string?> SendEmailViaGmailApi(
        EmailConfiguration config,
        ServiceDeskDbContext context,
        string toEmail,
        string subject,
        string htmlBody,
        int? ticketId = null,
        string? inReplyTo = null,
        string? references = null,
        CancellationToken ct = default)
    {
        var accessToken = await EnsureValidAccessToken(context, config, ct);
        if (string.IsNullOrEmpty(accessToken)) return null;

        // Build RFC 2822 message
        var boundary = $"----=_Part_{Guid.NewGuid():N}";
        var msgBuilder = new StringBuilder();

        // Generate a unique Message-ID
        var ourMessageId = $"<ss-{ticketId?.ToString() ?? "noreply"}-{Guid.NewGuid():N}@servicesphere.local>";

        msgBuilder.AppendLine($"From: ServiceSphere IT Support <{config.EmailAddress}>");
        msgBuilder.AppendLine($"To: {toEmail}");
        msgBuilder.AppendLine($"Subject: {EncodeMailHeaderValue(subject)}");
        msgBuilder.AppendLine($"Message-ID: {ourMessageId}");

        // Threading headers
        if (!string.IsNullOrEmpty(inReplyTo))
        {
            msgBuilder.AppendLine($"In-Reply-To: {inReplyTo}");
        }
        if (!string.IsNullOrEmpty(references))
        {
            msgBuilder.AppendLine($"References: {references}");
        }

        // Anti-loop header
        msgBuilder.AppendLine($"{AutoGeneratedHeader}: true");
        msgBuilder.AppendLine("MIME-Version: 1.0");
        msgBuilder.AppendLine($"Content-Type: multipart/alternative; boundary=\"{boundary}\"");
        msgBuilder.AppendLine();
        msgBuilder.AppendLine($"--{boundary}");
        msgBuilder.AppendLine("Content-Type: text/html; charset=UTF-8");
        msgBuilder.AppendLine("Content-Transfer-Encoding: base64");
        msgBuilder.AppendLine();
        msgBuilder.AppendLine(Convert.ToBase64String(Encoding.UTF8.GetBytes(htmlBody)));
        msgBuilder.AppendLine($"--{boundary}--");

        var rawMessage = Convert.ToBase64String(Encoding.UTF8.GetBytes(msgBuilder.ToString()))
            .Replace('+', '-')
            .Replace('/', '_')
            .TrimEnd('=');

        using var httpClient = _httpClientFactory.CreateClient();
        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

        var sendUrl = "https://gmail.googleapis.com/gmail/v1/users/me/messages/send";
        var requestBody = JsonSerializer.Serialize(new { raw = rawMessage });
        var content = new StringContent(requestBody, Encoding.UTF8, "application/json");

        var response = await httpClient.PostAsync(sendUrl, content, ct);
        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync(ct);
            _logger.LogError("Failed to send email via Gmail API: {Error}", error);
            return null;
        }

        // Parse sent message ID from response
        var responseJson = await response.Content.ReadAsStringAsync(ct);
        var responseData = JsonSerializer.Deserialize<JsonElement>(responseJson);
        var sentGmailId = responseData.TryGetProperty("id", out var idProp) ? idProp.GetString() : null;

        // Record outbound email for threading (only when linked to a ticket)
        if (ticketId.HasValue)
        {
            var ticketEmail = new TicketEmail
            {
                TicketId = ticketId.Value,
                GmailMessageId = sentGmailId ?? $"sent-{Guid.NewGuid():N}",
                MessageId = ourMessageId,
                InReplyTo = inReplyTo,
                References = references,
                FromAddress = config.EmailAddress,
                FromName = "ServiceSphere IT Support",
                Subject = subject.Length > 500 ? subject[..500] : subject,
                Direction = "Outbound",
                ProcessedDate = DateTime.UtcNow
            };
            context.TicketEmails.Add(ticketEmail);
            await context.SaveChangesAsync(ct);
        }

        return ourMessageId;
    }

    /// <summary>
    /// Exchanges an authorization code for tokens during the OAuth flow.
    /// </summary>
    public async Task<(bool Success, string? Error)> ExchangeAuthorizationCode(
        EmailConfiguration config,
        string authorizationCode,
        string redirectUri,
        CancellationToken ct = default)
    {
        using var httpClient = _httpClientFactory.CreateClient();
        var tokenRequest = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            ["code"] = authorizationCode,
            ["client_id"] = config.GmailClientId!,
            ["client_secret"] = config.GmailClientSecret!,
            ["redirect_uri"] = redirectUri,
            ["grant_type"] = "authorization_code"
        });

        var response = await httpClient.PostAsync("https://oauth2.googleapis.com/token", tokenRequest, ct);
        var responseBody = await response.Content.ReadAsStringAsync(ct);

        if (!response.IsSuccessStatusCode)
        {
            return (false, $"Token exchange failed: {responseBody}");
        }

        var tokenData = JsonSerializer.Deserialize<JsonElement>(responseBody);
        config.GmailAccessToken = tokenData.GetProperty("access_token").GetString();
        config.GmailRefreshToken = tokenData.GetProperty("refresh_token").GetString();
        var expiresIn = tokenData.GetProperty("expires_in").GetInt32();
        config.GmailTokenExpiry = DateTime.UtcNow.AddSeconds(expiresIn);
        config.IsAuthorized = true;

        // Get initial historyId by listing a single message
        try
        {
            var hc = new HttpClient();
            hc.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", config.GmailAccessToken);
            var profileResp = await hc.GetAsync("https://gmail.googleapis.com/gmail/v1/users/me/profile", ct);
            if (profileResp.IsSuccessStatusCode)
            {
                var profileJson = await profileResp.Content.ReadAsStringAsync(ct);
                var profileData = JsonSerializer.Deserialize<JsonElement>(profileJson);
                if (profileData.TryGetProperty("historyId", out var hid))
                {
                    config.GmailHistoryId = hid.GetString();
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not fetch initial historyId. Will use full sync on first poll.");
        }

        return (true, null);
    }

    #endregion

    #region Parsing Helpers

    /// <summary>
    /// Encodes a mail header value using RFC 2047 base64 encoding when it contains
    /// non-ASCII characters (e.g. em dashes, accented letters, emoji).
    /// Pure-ASCII values are returned unchanged.
    /// </summary>
    private static string EncodeMailHeaderValue(string value)
    {
        if (value.All(c => c < 128))
            return value;
        var encoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(value));
        return $"=?utf-8?B?{encoded}?=";
    }

    private static string GetHeader(List<GmailHeader> headers, string name)
    {
        return headers.FirstOrDefault(h =>
            h.Name.Equals(name, StringComparison.OrdinalIgnoreCase))?.Value ?? "";
    }

    private static (string Email, string? Name) ParseEmailAddress(string fromHeader)
    {
        if (string.IsNullOrWhiteSpace(fromHeader))
            return ("unknown@unknown.com", null);

        // Format: "Display Name <email@domain.com>" or "email@domain.com"
        var match = Regex.Match(fromHeader, @"(?:""?(.+?)""?\s*)?<(.+?)>");
        if (match.Success)
        {
            return (match.Groups[2].Value.Trim(), match.Groups[1].Value.Trim());
        }

        // Plain email
        var emailMatch = Regex.Match(fromHeader, @"[\w.+-]+@[\w.-]+\.\w+");
        return emailMatch.Success ? (emailMatch.Value, null) : (fromHeader.Trim(), null);
    }

    private static string CleanSubject(string subject)
    {
        // Remove Re:, Fwd:, Fw:, [#SS-XXXXX], etc.
        var cleaned = Regex.Replace(subject, @"^(Re:\s*|Fwd?:\s*)+", "", RegexOptions.IgnoreCase).Trim();
        cleaned = TicketRefRegex.Replace(cleaned, "").Trim();
        return cleaned;
    }

    private static bool IsAutoReply(List<GmailHeader> headers, string fromEmail)
    {
        // Check for auto-reply indicators
        var autoSubmitted = GetHeader(headers, "Auto-Submitted");
        if (!string.IsNullOrEmpty(autoSubmitted) && autoSubmitted != "no")
            return true;

        var precedence = GetHeader(headers, "Precedence");
        if (precedence.Equals("bulk", StringComparison.OrdinalIgnoreCase) ||
            precedence.Equals("junk", StringComparison.OrdinalIgnoreCase))
            return true;

        // Common no-reply addresses
        if (fromEmail.Contains("noreply", StringComparison.OrdinalIgnoreCase) ||
            fromEmail.Contains("no-reply", StringComparison.OrdinalIgnoreCase) ||
            fromEmail.Contains("mailer-daemon", StringComparison.OrdinalIgnoreCase) ||
            fromEmail.Contains("postmaster", StringComparison.OrdinalIgnoreCase))
            return true;

        return false;
    }

    /// <summary>Returns plain-text body for storage/search (stored in Description).</summary>
    private static string ExtractPlainBody(GmailFullMessage message)
    {
        var textBody = ExtractPartBody(message.Payload, "text/plain");
        if (!string.IsNullOrWhiteSpace(textBody))
            return textBody.Trim();

        // Fall back: strip HTML tags so Description always has readable text
        var htmlBody = ExtractPartBody(message.Payload, "text/html");
        if (!string.IsNullOrWhiteSpace(htmlBody))
        {
            var sanitizer = new HtmlSanitizer();
            var sanitized = sanitizer.Sanitize(htmlBody);
            return Regex.Replace(sanitized, "<[^>]+>", " ").Trim();
        }

        return "(No content)";
    }

    /// <summary>
    /// Returns sanitized HTML body for rich display (stored in DescriptionHtml).
    /// Returns null when only plain text is available.
    /// </summary>
    private static string? ExtractHtmlBody(GmailFullMessage message)
    {
        var htmlBody = ExtractPartBody(message.Payload, "text/html");
        if (string.IsNullOrWhiteSpace(htmlBody)) return null;

        var sanitizer = new HtmlSanitizer();
        // Allow safe styling attributes used by email clients
        sanitizer.AllowedAttributes.Add("style");
        sanitizer.AllowedAttributes.Add("align");
        sanitizer.AllowedAttributes.Add("width");
        sanitizer.AllowedAttributes.Add("height");
        sanitizer.AllowedAttributes.Add("cellpadding");
        sanitizer.AllowedAttributes.Add("cellspacing");
        sanitizer.AllowedAttributes.Add("border");
        sanitizer.AllowedAttributes.Add("bgcolor");
        sanitizer.AllowedTags.Add("table");
        sanitizer.AllowedTags.Add("thead");
        sanitizer.AllowedTags.Add("tbody");
        sanitizer.AllowedTags.Add("tr");
        sanitizer.AllowedTags.Add("td");
        sanitizer.AllowedTags.Add("th");
        sanitizer.AllowedTags.Add("img");
        sanitizer.AllowedAttributes.Add("src");
        sanitizer.AllowedAttributes.Add("alt");
        return sanitizer.Sanitize(htmlBody);
    }

    private static string? ExtractPartBody(GmailMessagePart? part, string mimeType)
    {
        if (part == null) return null;

        if (part.MimeType == mimeType && part.Body?.Data != null)
        {
            return DecodeBase64Url(part.Body.Data);
        }

        if (part.Parts != null)
        {
            foreach (var subPart in part.Parts)
            {
                var result = ExtractPartBody(subPart, mimeType);
                if (result != null) return result;
            }
        }

        return null;
    }

    private static string DecodeBase64Url(string base64Url)
    {
        var base64 = base64Url.Replace('-', '+').Replace('_', '/');
        var padLength = (4 - base64.Length % 4) % 4;
        base64 += new string('=', padLength);
        var bytes = Convert.FromBase64String(base64);
        return Encoding.UTF8.GetString(bytes);
    }

    private static void UpdateHistoryId(EmailConfiguration config, string? historyId)
    {
        if (!string.IsNullOrEmpty(historyId))
        {
            config.GmailHistoryId = historyId;
        }
    }

    /// <summary>
    /// Records what the poller did with a single inbound Gmail message. Called
    /// at every exit point of ProcessMessage so admins can audit (via the
    /// Settings → Inbound Email Log page) which messages were skipped and why.
    /// Adds to the DbContext without saving — the surrounding PollGmailInbox
    /// loop commits everything in one SaveChangesAsync at the end.
    /// </summary>
    private static void WriteInboundLog(
        ServiceDeskDbContext context,
        EmailConfiguration config,
        GmailMessage gmailMsg,
        GmailFullMessage? fullMessage,
        string? messageId,
        string? subject,
        string? fromAddress,
        InboundAction action,
        string? detail = null,
        string? error = null)
    {
        DateTime? received = null;
        if (fullMessage != null && fullMessage.InternalDate > 0)
        {
            received = DateTimeOffset.FromUnixTimeMilliseconds(fullMessage.InternalDate).UtcDateTime;
        }

        // Trim to schema-permitted lengths to avoid silent truncation surprises.
        string? Trim(string? s, int max) =>
            string.IsNullOrEmpty(s) ? s : (s.Length <= max ? s : s[..max]);

        context.InboundEmailLogs.Add(new InboundEmailLog
        {
            EmailConfigurationId = config.Id,
            GmailMessageId       = Trim(gmailMsg.Id, 100) ?? string.Empty,
            MessageId            = Trim(messageId,   500),
            Subject              = Trim(subject,     500),
            FromAddress          = Trim(fromAddress, 200),
            ReceivedDate         = received,
            ProcessedDate        = DateTime.UtcNow,
            Action               = action.ToString(),
            ActionDetail         = Trim(detail, 500),
            ErrorMessage         = Trim(error,  2000)
        });
    }

    #endregion

    #region Gmail API DTOs

    public class GmailMessage
    {
        public string Id { get; set; } = "";
        public string? ThreadId { get; set; }
    }

    public class GmailFullMessage
    {
        public string Id { get; set; } = "";
        public string? ThreadId { get; set; }
        public string? HistoryId { get; set; }
        // Unix epoch in milliseconds — returned by the Gmail API as "internalDate"
        public long InternalDate { get; set; }
        public GmailMessagePart? Payload { get; set; }
    }

    public class GmailMessagePart
    {
        public string? MimeType { get; set; }
        public List<GmailHeader> Headers { get; set; } = new();
        public GmailBody? Body { get; set; }
        public List<GmailMessagePart>? Parts { get; set; }
    }

    public class GmailHeader
    {
        public string Name { get; set; } = "";
        public string Value { get; set; } = "";
    }

    public class GmailBody
    {
        public string? Data { get; set; }
        public int Size { get; set; }
    }

    #endregion
}
